Repository codestates-seb/seb45_pre_017, pull requests merged in 2023-08, with the labels that each got.

#30 [FE] #10 Footer / view
  client/package.json
  client/src/App.tsx
  client/src/asset/stack-overflow.png
  client/src/components/Footer/index.tsx
Labels: frontend

#31 [FE] #9 우측 사이드바
  client/.eslintrc.js
  client/package-lock.json
  client/src/App.tsx
  client/src/asset/RightSidebar-firstSection.png
  client/src/asset/RightSidebar-firstSection02.jpeg
  client/src/asset/RightSidebar-firstSection03.png
  client/src/asset/RightSidebar-secondSection.png
  client/src/asset/RightSidebar-secondSection02.png
  client/src/asset/RightSidebar-secondSection03.png
  client/src/asset/index.tsx
  client/src/components/RightSidebar/DummyData.ts
  client/src/components/RightSidebar/FirstSection.tsx
  client/src/components/RightSidebar/FirstSectionContent.tsx
  client/src/components/RightSidebar/FirstSectionTitle.tsx
  client/src/components/RightSidebar/Index.tsx
  client/src/components/RightSidebar/SecondSection.tsx
  client/src/components/RightSidebar/SecondSectionContent.tsx
  client/src/components/RightSidebar/SecondSectionTitle.tsx
  client/src/components/index.tsx
  client/src/hooks/index.tsx
  client/src/models/index.tsx
  client/src/page/index.tsx
  client/src/reducer/index.tsx
  client/src/setupTests.ts
  client/src/store/index.tsx
  client/src/utils/index.tsx
  client/tsconfig.json
Labels: frontend

#33 #4 header
  .DS_Store
  client/src/App.tsx
  client/src/asset/Header-logo.png
  client/src/asset/Header-search.png
  client/src/components/Header/index.tsx
  package-lock.json
Labels: frontend

#37 [FE] #13 질문 상세 조회 페이지
  .DS_Store
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/asset/ContentViewForm-DummyProfile.jpeg
  client/src/components/AnswerContent/AnswerCounter.tsx
  client/src/components/AnswerContent/Index.tsx
  client/src/components/AnswerContent/dummyAnswer.ts
  client/src/components/AnswerWriteForm/Index.tsx
  client/src/components/AnswerWriteForm/WriteForm.tsx
  client/src/components/AskQuestionButton/Index.tsx
  client/src/components/ContentViewForm/Comment.tsx
  client/src/components/ContentViewForm/ContentVoteBar.tsx
  client/src/components/ContentViewForm/EditButton.tsx
  client/src/components/ContentViewForm/Index.tsx
  client/src/components/ContentViewForm/WriterProfile.tsx
  client/src/components/QuestionContent/Index.tsx
  client/src/components/QuestionContent/dummyQuestion.ts
  client/src/components/QuestionContentTitle/AdditionalInfo.tsx
  client/src/components/QuestionContentTitle/Index.tsx
  client/src/components/RightSidebar/FirstSectionTitle.tsx
  client/src/components/RightSidebar/SecondSectionTitle.tsx
  client/src/models/ContentProps.ts
  client/src/page/QuestionContentPage.tsx
  client/src/reportWebVitals.ts
Labels: frontend

#38 [FE] dev-fe#5/left sidebar
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Header/index.tsx
  client/src/components/LeftSidebar/LeftSidebarSvg.tsx
  client/src/components/LeftSidebar/index.tsx
Labels: frontend

#43 [FE] #8 메인페이지 뷰 완성
  client/src/App.tsx
  client/src/components/Main/DummyData.ts
  client/src/components/Main/Index.tsx
  client/src/components/Main/Post.tsx
  client/tsconfig.json
Labels: frontend

#45 [FE] Main 폴더 구조 변경
  client/src/App.tsx
  client/src/components/PostList/DummyData.ts
  client/src/components/PostList/Index.tsx
  client/src/page/Mainpage.tsx
Labels: frontend

#46 [FE] 질문 상세조회 페이지 레이아웃 완성
  client/src/App.tsx
  client/src/page/QuestionContentPage.tsx
Labels: frontend

#47 [BE] #23 Comment CRUD
  be-017-pre/build.gradle
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/controller/CommentController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentPostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/entity/Comment.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/mapper/CommentMapper.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/repository/CommentRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/service/CommentService.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/BusinessLogicException.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/ExceptionCode.java
  be-017-pre/src/main/resources/application.properties
  be-017-pre/src/main/resources/application.yml
Labels: backend

#49 [FE] #48 질문 상세조회 페이지 일부 수정
  client/src/components/ContentViewForm/AdditionalButton.tsx
  client/src/components/ContentViewForm/Comment.tsx
  client/src/components/ContentViewForm/EditButton.tsx
  client/src/components/ContentViewForm/Index.tsx
Labels: frontend

#51 [FE]#50 질문 상세조회 페이지 기본 통신로직 구현
  client/data/data.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Header/index.tsx
  client/src/components/PostList/Index.tsx
  client/src/hooks/useGetContent.ts
  client/src/index.tsx
  client/src/page/QuestionContentPage.tsx
Labels: frontend

#54 [BE] #21 Answer CRUD
  be-017-pre/build.gradle
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/controller/AnswerController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/dto/AnswerPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/dto/AnswerPostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/dto/AnswerResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/entity/Answer.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/mapper/AnswerMapper.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/repository/AnswerRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/service/AnswerService.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/controller/CommentController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentPostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/entity/Comment.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/repository/CommentRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/service/CommentService.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/ExceptionCode.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/GlobalExceptionAdvice.java
  be-017-pre/src/main/resources/application.yml
Labels: backend

#55 #21 Answer CRUD, #23 Comment CRUD
  be-017-pre/build.gradle
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/controller/AnswerController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/dto/AnswerPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/dto/AnswerPostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/dto/AnswerResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/entity/Answer.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/mapper/AnswerMapper.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/repository/AnswerRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/service/AnswerService.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/controller/CommentController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentPostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/dto/CommentResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/entity/Comment.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/mapper/CommentMapper.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/repository/CommentRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/service/CommentService.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/BusinessLogicException.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/ExceptionCode.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/GlobalExceptionAdvice.java
  be-017-pre/src/main/resources/application.properties
  be-017-pre/src/main/resources/application.yml
Labels: backend

#56 #27 Post CRUD
  .idea/git_toolbox_prj.xml
  .idea/misc.xml
  be-017-pre/build.gradle
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/BusinessLogicException.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/ExceptionCode.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/controller/PostController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/entity/Post.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/mapper/PostMapper.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/repository/PostRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/service/PostService.java
Labels: backend

#57 #27 Post CRUD
  be-017-pre/src/main/java/com/be017pre/be017pre/post/controller/PostController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/entity/Post.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/mapper/PostMapper.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/repository/PostRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/service/PostService.java
Labels: backend

#58 #27 Post CRUD
  be-017-pre/src/main/java/com/be017pre/be017pre/post/controller/PostController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostPatchDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/dto/PostResponseDto.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/entity/Post.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/mapper/PostMapper.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/repository/PostRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/service/PostService.java
Labels: backend

#53 [FE] #52 질문 상세 조회 페이지 Comment 관련 수정
  client/src/components/AnswerComment/AdditionalButton.tsx
  client/src/components/AnswerComment/Comment.tsx
  client/src/components/AnswerComment/CommentWriteForm.tsx
  client/src/components/AnswerComment/Index.tsx
  client/src/components/AnswerContent/Index.tsx
  client/src/components/ContentViewForm/Comment.tsx
  client/src/components/ContentViewForm/Index.tsx
Labels: frontend

#59 Post CRUD와 Comment,Answer CRUD 연결
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/controller/AnswerController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/entity/Answer.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/repository/AnswerRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/service/AnswerService.java
  be-017-pre/src/main/java/com/be017pre/be017pre/exception/ExceptionCode.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/controller/PostController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/entity/Post.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/repository/PostRepository.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/service/PostService.java
Labels: backend

#65 [FE] #64 로그아웃 페이지 뷰 구현
  client/src/App.tsx
  client/src/components/Header/index.tsx
  client/src/components/LogoutBox/Buttons.tsx
  client/src/components/LogoutBox/DomainList.tsx
  client/src/components/LogoutBox/Index.tsx
  client/src/components/LogoutBox/dummyDomain.ts
  client/src/page/LogoutPage.tsx
Labels: frontend

#61 [FE] 질문 작성페이지 뷰 구현 완료
  client/src/components/AskEditAdvice/Index.tsx
  client/src/components/AskEditAdvice/dummyAdvice.tsx
  client/src/components/AskEditAside/Index.tsx
  client/src/components/AskEditAside/dummyAskAside.tsx
  client/src/components/AskEditButton/Index.tsx
  client/src/components/AskEditForm/EditBox.tsx
  client/src/components/AskEditForm/Index.tsx
  client/src/components/AskEditForm/dummyForm.tsx
  client/src/page/AskEditPage.tsx
  package-lock.json
Labels: frontend

#66 Dev fe#10/footer/fix
  client/src/App.tsx
  client/src/components/Footer/index.tsx
  client/src/page/AskEditPage.tsx
  client/src/page/Mainpage.tsx
Labels: frontend

#67 [FE] 질문 작성 페이지 버튼 연결
  client/src/App.tsx
  client/src/components/AskQuestionButton/Index.tsx
Labels: frontend

#69 [FE] #68 질문 상세 조회 페이지 Footer 컴포넌트 배치
  client/src/components/Footer/index.tsx
  client/src/page/QuestionContentPage.tsx
Labels: frontend

#60 [FE} Dev fe#7/sign up
  client/.gitignore
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Header/index.tsx
  client/src/components/SignUp/Community.tsx
  client/src/components/SignUp/OauthButton.tsx
  client/src/components/SignUp/RegisterUser.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/components/SignUp/index.tsx
  client/src/page/SignUpPage.tsx
  package-lock.json
  package.json
Labels: frontend

#75 [FE] 화면 뷰 오류 수정
  client/src/page/AskEditPage.tsx
  client/src/page/Mainpage.tsx
Labels: bug

#73 [FE] #71 좌측 사이드바 디자인 수정
  client/src/components/AskEditButton/Index.tsx
  client/src/components/LeftSidebar/index.tsx
Labels: frontend

#76 [FE] 로그인 페이지 뷰
  client/src/App.tsx
  client/src/components/Login/LoginForm.tsx
  client/src/components/Login/OAuthButton.tsx
  client/src/components/Login/index.tsx
  client/src/page/LoginPage.tsx
  client/src/page/SignUpPage.tsx
Labels: frontend

#77 Feat : Cors 에러 처리 부분 추가
  be-017-pre/src/main/java/com/be017pre/be017pre/CorsInterceptor.java
  be-017-pre/src/main/java/com/be017pre/be017pre/WebConfig.java
  be-017-pre/src/main/java/com/be017pre/be017pre/answer/controller/AnswerController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/comment/controller/CommentController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/controller/PostController.java
  be-017-pre/src/main/java/com/be017pre/be017pre/post/service/PostService.java
Labels: backend

#79 [FE] #78 미구현 페이지 컴포넌트 생성
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/LeftSidebar/index.tsx
  client/src/page/NoExistPage.tsx
Labels: frontend

#81 [FE] 질문 수정, 답변 수정 페이지 뷰 구현
  client/src/App.tsx
  client/src/components/AskEditAside/Index.tsx
  client/src/page/AskModifyPage.tsx
Labels: frontend

#85 [FE] 회원가입 기능 구현
  client/Issue
  client/package-lock.json
  client/package.json
  client/src/components/Login/LoginForm.tsx
  client/src/components/Login/LoginUser.tsx
  client/src/components/LogoutBox/Buttons.tsx
  client/src/components/SignUp/RegisterUser.tsx
  client/src/components/SignUp/SignUpForm.tsx
  client/src/page/LogoutPage.tsx
  client/src/page/SignUpPage.tsx
Labels: frontend

#87 [FE] #86 질문 상세 조회 페이지 통신 로직 구현 (GET, POST 메서드)
  client/data/data.json
  client/package-lock.json
  client/src/App.tsx
  client/src/components/AnswerComment/Comment.tsx
  client/src/components/AnswerComment/CommentWriteForm.tsx
  client/src/components/AnswerComment/Index.tsx
  client/src/components/AnswerContent/AnswerCounter.tsx
  client/src/components/AnswerContent/Index.tsx
  client/src/components/AnswerWriteForm/Index.tsx
  client/src/components/AnswerWriteForm/WriteForm.tsx
  client/src/components/ContentViewForm/Index.tsx
  client/src/components/ContentViewForm/WriterProfile.tsx
  client/src/components/PostList/Index.tsx
  client/src/components/QuestionContent/Index.tsx
  client/src/components/QuestionContentTitle/Index.tsx
  client/src/hooks/useGetAnswer.ts
  client/src/hooks/useGetComment.ts
  client/src/hooks/useGetContent.ts
  client/src/hooks/useGetQuestion.ts
  client/src/hooks/usePostAnswer.ts
  client/src/hooks/usePostComment.ts
  client/src/models/ContentProps.ts
  client/src/page/QuestionContentPage.tsx
Labels: frontend
